name: Test Build Simple

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
      
      - name: Build pure Python package
        run: |
          echo "=== Building pure Python package ==="
          python setup.py bdist_wheel
          
      - name: List built wheels
        run: |
          echo "=== Built wheels ==="
          ls -la dist/
          
      - name: Test import
        run: |
          echo "=== Testing import ==="
          pip install dist/*.whl
          python -c "import django_mercury; print('Import successful!')"
          python -c "from django_mercury.python_bindings.c_bindings import HAS_C_EXTENSIONS; print(f'C extensions available: {HAS_C_EXTENSIONS}')"